# Generated by Django 5.0.1 on 2024-01-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=22)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to='media')),
                ('at_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
