# Generated by Django 5.0.1 on 2024-01-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Laptop',
        ),
    ]
